language: node_js
node_js:
  - stable

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - yarn install
  - yarn build

script:
  - chmod u+x deploy.sh
  - bash ./deploy.sh

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
#   target-branch: gh-pages
#   local-dir: .vuepress/dist
#   on:
branch: master